[build]
  base = "book"
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && jupyter-book build --html"
  environment = { PYTHON_VERSION = "3.13" }
  publish = "_build/html"

[[redirects]]
  from = "/95199651-9e81-4cae-a3a7-66398a9a5f62/*"
  to = "https://95199651-9e81-4cae-a3a7-66398a9a5f62.netlify.app/:splat"
  status = 200
  force = true