[build]
  base = "book"
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && jupyter-book build --html"
  environment = { PYTHON_VERSION = "3.13" }
  publish = "_build/html"

[[redirects]]
  from = "/*"
  to = "https://eds-book.github.io/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/gallery/67a1e320-7c47-4ea9-8df8-e868326bc90b/*"
  to = "https://eds-book.github.io/67a1e320-7c47-4ea9-8df8-e868326bc90b/:splat"
  status = 200
  force = false

#[[redirects]]
#  from = "/build/*"
#  to = "https://95199651-9e81-4cae-a3a7-66398a9a5f62.netlify.app/:splat"
#  status = 200
#  force = false

#[[redirects]]
#  from = "/gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/*"
#  to = "https://95199651-9e81-4cae-a3a7-66398a9a5f62.netlify.app/:splat"
#  status = 200
#  force = false
#
#[[redirects]]
#  from = "/build/*"
#  to = "https://95199651-9e81-4cae-a3a7-test/:splat"
#  status = 200
#  force = false
#
#[[redirects]]
#  from = "/gallery/95199651-9e81-4cae-a3a7-test/*"
#  to = "https://95199651-9e81-4cae-a3a7-test.netlify.app/:splat"
#  status = 200
#  force = false

#[[redirects]]
#  from = "/gallery/ea34568e-d86e-4720-be2f-3f826f66a26c/*"
#  to = "https://ea34568e-d86e-4720-be2f-3f826f66a26c.netlify.app/:splat"
#  status = 200
#  force = false
