[build]
  base = "book"
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && jupyter-book build --html"
  environment = { PYTHON_VERSION = "3.13" }
  publish = "_build/html"

#[[redirects]]
#  from = "/build/*"
#  to = "https://95199651-9e81-4cae-a3a7-66398a9a5f62.netlify.app/build/:splat"
#  status = 200
#  force = false

[[redirects]]
  from = "/gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/*"
  to = "https://95199651-9e81-4cae-a3a7-66398a9a5f62.netlify.app/:splat"
  status = 200
  force = false

#[[redirects]]
#  from = "/gallery/39d9c177-11da-41b2-9b64-63f4c1c834b3/*"
#  to = "https://39d9c177-11da-41b2-9b64-63f4c1c834b3.netlify.app/:splat"
#  status = 200
#  force = false
#
#[[redirects]]
#  from = "/gallery/ea34568e-d86e-4720-be2f-3f826f66a26c/*"
#  to = "https://ea34568e-d86e-4720-be2f-3f826f66a26c.netlify.app/:splat"
#  status = 200
#  force = false
